name: turisgo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    


  flutter_localizations:
    sdk: flutter

  supabase_flutter: ^2.3.4
  mailer: ^6.0.0
  google_maps_flutter: ^2.5.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flip_card: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lottie: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/desierto.jpg
    - assets/sena.jpg
    - assets/vivi.jpeg
    - assets/Bogota.jpg
    - assets/Medellin.jpg
    - assets/Cartagenadeindias.jpg
    - assets/cali.jpg
    - assets/kia.jpg
    - assets/restaurante.jpg
    - assets/hotel.jpg
    - assets/China.jpg
    - assets/Canada.jpg
    - assets/Paris.jpg
    - assets/Italia.jpg
    - assets/hotel3.jpg
    - assets/hotel2.jpg
